Put spans to the queue in non-blocking mode
wavefrontHQ/wavefront-opentracing-sdk-python pull request #60
Opened 2021-12-22 12:19 UTC by alexey-stankevich

Fixes #59

2021-12-22 12:21 UTC, insfor approved these changes

2022-04-18 17:23 UTC, keep94 commented
Hi, @alexey-stankevich, your PR looks good and we plan to merge it, but first will you use put_nowait() instead of put(..., block=FALSE)?  The first is more readable in my opinion. Also, we use put_nowait() in other wavefront python libraries we maintain, so it will make everything more consistent.  Thank you.

2022-04-18 17:27 UTC, keep94 requested changes

2022-04-18 17:27 UTC, keep94 commented on wavefront_opentracing_sdk/reporting/wavefront.py
> +            self._span_buffer.put(wavefront_span, block=False)
Please use put_nowait() here.

2022-04-19 00:02 UTC, keep94 commented
Closing this PR as it is superseded by PR #62.  This PR was too old to merge.  Thank you again for your contribution.

2022-04-19 20:01 UTC, closed without merging